### PR TITLE
'Upload' Option and Admin Panel Tweaks

### PR DESCRIPTION
**Pull request by ardalann**
- New attribute for allowed mime type ('image' by default, can be set to null or "" to allow any mime type)
- The plus icon is now hidden when a file is selected (before, it could be seen when selected image was transparent)
- Renamed the css file (it was mistakenly named option-font)

I tried to keep the changes to a minimum and use the same functions WP uses in wp-includes/media.php.

### CODE REVIEW

**Comment by ardalann** [comment]
Important Note: I didn't update the controller for customizer.

**Comment by ardalann** [comment]
Added: Display filename when selected file is not an image

**Comment by ardalann** [comment]
Fixed: Long file names don't go outside the thumbnail div

**Comment by shuvo586** [comment]
I am not getting any file. output is blank .

**Comment by shuvo586** [comment]
Recently i worked for a website. To get uploaded audio i added following code and i worked.But is there any better way to output uploaded file ?
```php
<?php 
	$titan = TitanFramework::getInstance( 'my-theme' );
	$uploaded_file = $titan->getOption( 'my_upload_option' );
	$upload_dir = wp_upload_dir();
	$file_path = basename( get_attached_file( $uploaded_file ) );
?>
<audio controls="controls">
	<source src="<?php echo $upload_dir['url'].'/'.$file_path ?>"  type="audio/mpeg">
</audio>
```

**Comment by bfintal** [comment]
Hi @ardalann I'm sorry this is taking so long. If you can update this then I'm going to merge it

**Comment by ardalann** [comment]
Hi @bfintal . When I submitted this pull request there was no conflict. What is the conflict now? I can't seem to find it anywhere (I am using the web interface. Haven't installed the Github software)

**Comment by bfintal** [comment]
We had some code restructuring and optimizations done, e.g. `TitanFramework::$initializing` was removed, option PHP files and others have been moved to the `lib` folder.

**Comment by ardalann** [comment]
@bfintal Sounds good!
Sorry but I don't have time to work on this right now. I added you to my forked TF as a collaborator so you can make changes if you want.

**Comment by rahmanQaiser** [comment]
Is Framework pre svg supported?

**Comment by ReggieDuran** [comment]
@ardalann @rahmanQaiser We've merged pr #351  file upload option and allowed svg in upload option. db3453ac81a11765e98742ec6da009b195e3d4f7.

**Pull request closed without merging**
