### PR TITLE
File upload option added

### PR DESCRIPTION
**Pull request by hsleonis**
**New Feature:**
Easily upload any files with media uploader.

Usage:
```php
$section->createOption( array(
		'name' => 'PDF',
		'id' => 'sec_pdf_upload',
		'type' => 'file',
		'desc' => 'Upload your resume'
	) );
```

### CODE REVIEW

**Comment by hsleonis** [comment]
@gambitph this code is similar to the 'Upload' option.
Please check 'travis-ci' error: PHP 5.2 not installed.

**Comment by ReggieDuran** [comment]
travis doesn't have 5.2 anymore :(

**Comment by hsleonis** [comment]
Yes! @ReggieDuran

**Comment by hsleonis** [comment]
@ReggieDuran please merge #56795ce

**Comment by ReggieDuran** [comment]
@hsleonis it's already merged

**Comment by hsleonis** [comment]
Great! :)
Thanks @ReggieDuran, can you please add me to the contributor list at http://www.titanframework.net

Regards.

**Comment by ReggieDuran** [comment]
You're already added 👍

**Comment by hsleonis** [comment]
Thanks @ReggieDuran :)

**Comment by hsleonis** [comment]
Hi @ReggieDuran bro, couldn't find myself on the contributor list at http://www.titanframework.net
Can you please check?

**Pull request merged**
