### PR TITLE
Possibility to use sanitization function in customizer

### PR DESCRIPTION
**Pull request by limestreet**
It's really important to have secure option framework, so i'm proposing this pull request as a security improvement. More info here:
https://make.wordpress.org/themes/2015/06/02/a-guide-to-writing-secure-themes-part-3-sanitization/

P.S. Other parts of series:
https://make.wordpress.org/themes/2015/05/19/a-guide-to-writing-secure-themes-part-1-introduction/
https://make.wordpress.org/themes/2015/05/26/a-guide-to-writing-secure-themes-part-2-validation/
https://make.wordpress.org/themes/2015/06/09/a-guide-to-writing-secure-themes-part-4-securing-post-meta/

### CODE REVIEW

**Comment by julien731** [comment]
Completely agree with that but I can't see where the sanitization is done here. Am I missing something?

**Comment by limestreet** [comment]
Hi @julien731 

in customizer api there is add_setting method with parameter sanitize_callback where you can pass name of function which has to be used to sanitize value. In Titan Framework "livepreview" is working vary similar.

**Comment by limestreet** [comment]
One more thing - is not possible to provide default sanitization i.e. for select, multicheckbox...
When you are building options you can pass (via proposed parameter) WordPress native functions to sanitize or build your own and pass to customizer...

**Comment by limestreet** [comment]
I think that lack of using "sanitize_callback" is the biggest blocker to grow for Titan - it's the biggest reason why no one from wp.org authors repo cannot use titan to build theme options...

**Comment by bfintal** [comment]
I'm all for this sanitization.

So basically, we're just adding a way for people to define a `sanitize_callback` parameter and nothing else? Similar to the `sanitize_callbacks` parameter for the text option? How about we just merge the two instead?

@limestreet I think there's no need to sanitize select and multicheckbox options though. The output of those are defined by the way the option was created unlike text inputs where you won't know what the user is going to input.

I'm not sure if that's the reason though why people aren't using Titan for themes in wp.org. It may just be that nobody knows about Titan Framework. haha! I actually have a theme in wp.org which isn't yet accepted after getting reviewed and needs a bit of fixing in order to continue. Good news is that using Titan and the stuff which need to be fixed have nothing to do with the framework used.

**Comment by bfintal** [comment]
I can merge this, but I think this should be also extended further into the admin page and meta boxes instead of just the Customizer.

@limestreet & @julien731 What if we drop the `sanitize_callbacks` parameter in the text option (support it for backward compatibility), then use `sanitize_callback` instead of `sanitize` then call the sanitizing function in the `getValue` function inside *class-option.php* but just for getting values in admin pages and meta boxes. Customizer options are already handled using the proposed change so no need to add it.

**Comment by julien731** [comment]
Agreed with `sanitize_callback`. Shouldn't the value be sanitized before being saved to the database (`setValue`?) though?

**Comment by bfintal** [comment]
@julien731 lol! I was thinking of setValue the whole time, but managed to comment differently

**Comment by julien731** [comment]
Then I think your previous comment makes total sense. I'd definitely go for it.

**Comment by limestreet** [comment]
```sanitize_callback``` is all what I ask for. It will be very helpful for theme designer to pass values to ```sanitize_callback``` (even custom functions - this is what theme designers do now when interacting with customizer api). This is prompted by "Theme Check" as well...

**Comment by limestreet** [comment]
I did read now all your comments ;P

For me the most important thing was problem with Theme Check and wp.org themes repo where every ```add_setting``` value should be sanitized via ```sanitize_callback```

**Comment by limestreet** [comment]
@bfintal you mentioned earlier "Customizer options are already handled using the proposed change so no need to add it." What do you mean by this?? There is any method in TF to pass sanitize function name to Customizer's ```sanitize_callback```??

**Comment by ReggieDuran** [comment]
2f7e8172ada34286e0a187825dda92a0ac18b9b4 921adefafd255ca094b76b905827fca3a5b0a3a9

**Pull request closed without merging**
